### ISSUE TITLE
Broken in 1.9

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleTracker#15]
Broken and breaks battlearena if you try to use it.

**Comment by Zach443** [comment]
I fixed some 1.9 related issues in that commit. Jar is pending on Bukkit and already available on the Spigot page. Let me know if that solves your issues.

**Comment by tara81** [comment]
sweeet thanks for the quick update !

**Comment by tara81** [comment]
It still doesn't load. I think herochat related.

BattleTracker doesnt work : Latest:
http://pastebin.com/3B5xnS05
(Herochat intergration fail- theres a new herochat update)

BombArena Errors - Fails to Load:
http://pastebin.com/nHAvVARZ

Most recent herochat version : 
http://dev.bukkit.org/bukkit-plugins/herochat/

**Comment by Zach443** [comment]
@tara81 Thanks, looking at the HeroChat stuff now. BombArena actually has it's own repository over on @Europia79 's account. Try asking about stuff there.

**Comment by Kainzo** [comment]
I suggest updating to the legacy version of Herochat.

**Comment by tara81** [comment]
thanks kainzo, as soon as I saw your post i actually looked at herochat for updates and saw there is a legacy version now that appears to work with battletracker :) I guess you guys can close this !  I cannot seem to get faction tags to work for some odd reason tho (unrelated to this bug report)
